package com.internal.playment.common.enums;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class SystemConstant implements Serializable {
    public static final String SQUARE_ENABLE = "0";
    public static final String DIS_ENABLE = "1";
    public static final String DIS_CHECK = "2";
    public static final Integer NO_PAY = 2;
    public static final Integer NO_SETTLE = 0;
    public static final Integer MQ_PROCESSED = 20;
    public static final Integer MQ_PROCESSED_23 = 23;
    public static final Integer MQ2_PROCESSED = 30;
    public static final Integer MQ2_PROCESSED_33 = 33;
    public static final Integer MQ_EXCEPITON_PROCESSED = 40;
    public static final Integer DRAW_WAIT_AUDIT = 0;
    public static final Integer DRAW_WAIT_PAY = 1;
    public static final Integer DRAW_PAY_SUCCESS = 2;
    public static final Integer DRAW_NO_SUCCESS = 3;
    public static final String[] SQUARE_REF_TYPE = new String[]{"通道", "商户"};
    public static final String BONDCARD = "1";
    public static final String ADDCUS = "2";
    public static final Integer CHANNEL_XINSHENG = 6;
    public static final String payId = "PAY_ID";
    public static final String customerId = "CUSTOMER_ID";
    public static final String id = "ID";
    public static final String name = "NAME";
    public static final String exceptionId = "EXCEPTION_ID";
    public static final String type = "TYPE";
    public static final String remark = "REMARK";
    public static final String sysId = "SYSID";
    public static final String returnUrl = "RETURNURL";
    public static final String noticeUrl = "NOTICEURL";
    public static final String orderTrackStatus = "ORDERTRACKSTATUS";
    public static final String tradeInfo = "tradeinfo";
    public static final String refer = "REFER";
    public static final String CORRECT = "6";
    public static final String DARW_MONEY = "7";
    public static final String organizationName = "ORGANIZATION_NAME";
    public static final String merId = "MER_ID";
    public static final String merOrderId = "MER_ORDER_ID";
    public static final String channelName = "CHANNEL_NAME";
    public static final String DRAWSTATUS = "drawStatus";
    public static final String payType = "PAY_TYPE";
    public static final String channelTransCode = "CHANNEL_TRANS_CODE";
    public static final String income = "income";
    public static final String SUCCESS = "0";
    public static final Integer ENABLE = 0;
    public static final Integer DISABLE = 1;
    public static final String FAIL = "1";
    public static final long SECOND_TO_MILLISECOND = 1000L;
    public static final long MINUTE_TO_MILLISECOND = 60000L;
    public static final long HOUR_TO_MILLISECOND = 3600000L;
    public static final String ROLE_INTERNAL_ADMIN = "ROLE_INTERNAL_ADMIN";
    public static final String ROLE_INTERNAL_USER = "ROLE_INTERNAL_USER";
    public static final String ROLE_MERCHANT_ADMIN = "ROLE_MERCHANT_ADMIN";
    public static final String ROLE_MERCHANT_USER = "ROLE_MERCHANT_USER";
    public static final long ROLE_ADMIN_ID = 777L;
    public static final short ORDER_CHANGE_STATUS_UNAUDITED = 0;
    public static final short ORDER_CHANGE_STATUS_SUCCESSFUL = 1;
    public static final short ORDER_CHANGE_STATUS_FAIL = 2;
    public static final short ORDER_CHANGE_STATUS_PROCESSING = 3;
    public static final short PASSED = 1;
    public static final short DID_NOT_PASS = 2;
    public static final short EXCEPTION_STATUS_NORMAL = 0;
    public static final short EXCEPTION_STATUS_FREEZE = 1;
    public static final short EXCEPTION_STATUS_REFUND = 2;
    public static final short EXCEPTION_STATUS_REFUSED = 4;
    public static final short TRANSACTION_RATE = 0;
    public static final short SETTLEMENT_RATE = 1;
    public static final short FUNDING_RATE = 2;
    public static final short FULL_REFUND = 2;
    public static final short PARTIAL_REFUND = 3;
    public static final short FULL_REFUSED = 4;
    public static final short PARTIAL_REFUSED = 5;
    public static final short PROXY_REFUSED = 6;
    public static final short BANK_PROCESSING_REFUND = 7;
    public static final String CURRENCY_CNY = "CNY";
    public static final String CURRENCY_USD = "USD";
    public static final short STATUS_ENABLE = 1;
    public static final int LIMIT_EVERY = 0;
    public static final int LIMIT_DAY = 1;
    public static final int LIMIT_MONTH = 2;
    public static final int LIMIT_YEAR = 3;
    public static final String[] REF_TYPE = new String[]{"通用", "收单机构", "商户", "域名"};
    public static final String REMITTANCE = "Remittance";
    public static final String BANK_STATUS = "BankStatus";
    public static final String SHIP_STATUS = "ShipStatus";
    public static final short SHIP_STATUS_SHIPPED = 1;
    public static final short REFUND_STATUS_DID_NOT_PASS = 2;
    public static final short REFUND_STATUS_BANK_PROCESSING = 3;
    public static final short EXCEPTION_STATUS_REFUND_PROCESSING = 7;
    public static final String FINANCE_STATUS = "FinanceStatus";
    public static final String CONTINENT = "Continent";
    public static final String CURRENCY = "Currency";
    public static final String LANG = "Lang";
    public static final String COUNTRY = "Country";
    public static final String QUICK_TEST = "QuickTest";
    public static final String ACQUIRER_TYPE = "AcquirerType";
    public static final String CURRENCY_TYPE = "CurrencyType";
    public static final String RISK = "Risk";
    public static final String STATUS = "Status";
    public static final String availableStatus = "availableStatus";
    public static final String channelLevel = "channelLevel";
    public static final String PAYTYPE = "PayType";
    public static final String DETAILSTYPE = "detailsType";
    public static final String BUSITYPE = "busiType";
    public static final String EXTRATYPE = "extraType";
    public static final String BUSSTYPE = "bussType";
    public static final String PRODUCTTYPE = "productType";
    public static final String ORDERSTATUS = "orderStatus";
    public static final String SETTLESTATUS = "settleStatus";
    public static final String MERCHANTTYPE = "merchantType";
    public static final String IDENTITYTYPE = "identityType";
    public static final String BANKCARDTYPE = "bankcardType";
    public static final String MERCHANT_STATUS = "MerchantStatus";
    public static final short BANK_STATUS_SUCCESS = 0;
    public static final short BANK_STATUS_FAIL = 1;
    public static final short BANK_STATUS_UNPAID = 2;
    public static final short BANK_STATUS_PENDING_PAYMENT = 3;
    public static final short BANK_STATUS_TIME_OUT = 98;
    public static final short BANK_STATUS_RESEND = 4;
    public static final short LOG_LOGIN = 0;
    public static final short LOG_ADD = 1;
    public static final short LOG_DELETE = 2;
    public static final short LOG_UPDATE = 3;
    public static final short LOG_READ = 4;
    public static final short LOG_UNKNOWN_METHOD = 8;
    public static final short LOG_ERROR = 9;
    public static final short FINANCE_DRAWING_TYPE_MERCHANT = 1;
    public static final short FINANCE_DRAWING_TYPE_INTERNAL = 2;
    public static final String COUNRTY_CODE_CHN = "CHN";
    public static final String QUESTION_TYPE = "QuestionType";
    public static final String QUESTION_STATUS = "QuestionStatus";
    public static final short PAY_STATUS_GATEWAY = 0;
    public static final short PAY_STATUS_PAGE = 1;
    public static final short PAY_STATUS_RISK = 2;
    public static final short PAY_STATUS_OUTLAY = 3;
    public static final short PAY_STATUS_SEND = 4;
    public static final short PAY_STATUS_RESPONSE = 5;
    public static final short PAY_STATUS_RETURN = 6;
    public static final short INTERFACE_REDIRECT = 0;
    public static final short INTERFACE_INNER = 1;
    public static final short CHANGE_BANK_STATUS_FAIL = 2;
    public static final Integer CUS_USABLE = 0;
    public static final Integer CUS_DISABLE = 1;
    public static final Integer CUS_PROCESSD = 2;
    public static final String INFORMATION_REGISTRATION = "J001";
    public static final String BANKCARD_REGISTRATION = "J002";
    public static final String SERVICE_FULFILLMENT = "J003";
    public static final String BONDCARD_APPLY = "B001";
    public static final String BONDCARD_SMS = "B002";
    public static final String BONDCARD_CONFIRM = "B003";
    public static final String PAY_APPLY = "P001";
    public static final String PAY_SMS = "P002";
    public static final String PAY_CONFIRM = "P003";
    public static final String GENERATION_PAY = "D001";
    public static final Map<String, String> PAY_TYPE_MAP = new HashMap<String, String>() {
        {
            this.put("COMMON", "0");
            this.put("VISA", "1");
            this.put("MASTER", "2");
            this.put("JCB", "3");
        }
    };

    public SystemConstant() {
    }
}
